### ISSUE TITLE
Bug Report 서버측 개발

### ISSUE THREAD

**Issue by HosikChae** [KNPAPS/Romeo-Android#13]
Data reqData = new Data()
    .add(0, KEY.MESSAGE.SENDER_IDX, UserInfo.getUserIdx(getActivity())) (
    .add(0, KEY.MESSAGE.CREATED_TS, Calendar.getInstance().getTime())
    .add(0, KEY.MESSAGE.CONTENT, content.getText().toString());

Payload request = new Payload().setEvent("BUG:REPORT").setData(reqData);

클라이언트 상에서는 이런 코드로 보내게 됨.
KEY.MESSAGE.SENDER_IDX : Message_senderIdx
KEY.MESSAGE.CREATED_TS : Message_TS
KEY.MESSAGE.CONTENT : Message_content
인 것으로 알고 있음.

**Comment by yw-choi** [comment]
https://docs.google.com/document/d/1pYVWM1wWQ0ZtoF-B6Y1JrFmkOO-J_T47Ua8Iim5WzD8/edit
