### ISSUE TITLE
설문 결과 어떻게 보일건지 만들기

### ISSUE THREAD

**Issue by HosikChae** [KNPAPS/Romeo-Android#21]
뭐하라는거였지????

**Comment by HosikChae** [comment]
수신자가 볼 수 있는지 없는지 ㅇㅇ

**Comment by yw-choi** [comment]
서버 작업:
constants.php
class KEY_SURVEY에
const KEY_SURVEY::IS_RESULT_PUBLIC = "Survey_isResultPublic"  추가

DB에
altert table js_survey add column is_result_public tinyint default 0 추가
