### ISSUE TITLE
버그 리포팅 메뉴 추가

### ISSUE THREAD

**Issue by yw-choi** [KNPAPS/Romeo-Android#4]
기본기능
- 메인메뉴의 가장 아래쪽에 하나 추가
- 카테고리 및 상세한 설명을 써서 보내면 서버 DB에 저장되어 나중에 참고할 수 있게

**Comment by yw-choi** [comment]
@gimoon 
이기문님 버그리포팅 메뉴에 들어갈 아이콘 디자인 부탁드립니다.

참고: 페이스북 App에서 폰의 '메뉴' 버튼을 눌렀을 때 뜨는 '버그 신고하기' 메뉴의 아이콘과 비슷한 디자인이어도 괜찮을 것 같고 아니면 그냥 느낌표 모양이어도 괜찮을 것 같습니다.

**Comment by HosikChae** [comment]
@projet6634 기문이가 알림 안간다고해서 하는 테스트

**Comment by gimoon** [comment]
기문이가 알림 안간다고 하다니 이런 뭐같은.
만들어 드리리다~

**Comment by gimoon** [comment]
최영우님 메일 보냈습니다. 확인부탁드려요

**Comment by yw-choi** [comment]
@gimoon 메일 받았습니다.
그리고 멘션하실때 페북처럼 @하고 아이디 치시면 알림이 바로 갑니다 ㅋㅋ

**Comment by HosikChae** [comment]
@projet6634 이런거 깃헙 에이피아이 같은거 써서 바로 여기에 등록하게 안되나?
뭐 안되면.. 글타래같이 출력하게해서 김영우보고 필터링해서 여따 올리라해야지모 ㅋㅋ
