### ISSUE TITLE
설문조사 삭제 기능

### ISSUE THREAD

**Issue by yw-choi** [KNPAPS/Romeo-Android#43]

**Comment by HosikChae** [comment]
SurveyFragment.init (...) {... listView.setOnItemLongClick() { ... 에 있는 TODO 보면 
DB에서 해당 설문조사만 지울 수 있으면 되게 해놨음.

**Comment by HosikChae** [comment]
SurveyIdx 나 Survey 중 아무거나 사용해서 쓰면 됨
